apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: chandru27/wisecow:latest   # 👈 change to your Docker Hub repo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4499
